### ISSUE TITLE
support forcibly disconnecting clients from the server side

### ISSUE THREAD

**Issue by seiyria** [gamestdio/colyseus#100]
this would be beneficial in a case where you have a game where users have a more permanent session, and they might log in from one computer, then want to log in from another one. ideally, the second login would kick off the connection from the first one. 

right now, all I can do is block the client from connecting multiple times, but I'd rather err on the side of kicking than blocking.

**Comment by IceAquaria** [comment]
Yes, PLEASE add this!

**Comment by endel** [comment]
@seiyria @IceAquaria 

If you can get the other `client` instance based on a criteria (having the same `client.id`, or the same user id in case of authentication), you can manually call `client.close()` on the first instance.

The client shouldn't try to reconnect after the server closes the connection via `client.close()`.

Do you guys think this should be part of the room API somehow?

**Comment by seiyria** [comment]
I don't know if that's necessary if it's possible to kill them now. I think
it merits some explanation what you can do with a websocket, though.

**Comment by endel** [comment]
Closing as we already have this: http://colyseus.io/docs/api-client/#closecode-number

**Comment by Elyx0** [comment]
Where does it point now? Randomly found this looking for how to detect state / connections hiccups with Colyseus to warn the user.

When I CTRL+C my nodejs server,  what should I listen for client-side to know that I lost connection after the initial connect?

**Comment by endel** [comment]
Hi @Elyx0, you are probably looking for `room.onLeave()` on the client-side. When the connection is closed a `code` is provided with the reason of the closure. (probably higher than 1000 by hitting Ctrl+C) https://docs.colyseus.io/client/room/#onleave
