### ISSUE TITLE
Simulation Interval Efficiency

### ISSUE THREAD

**Issue by oyed** [gamestdio/colyseus#101]
As per the simulation interval: https://github.com/gamestdio/colyseus/blob/master/src/Room.ts#L65

Might it be worth taking an approach similar to [node-gameloop](https://github.com/tangmi/node-gameloop) for efficiency?

**Comment by endel** [comment]
Hey, I'm cleaning up the old issues. We would need some benchmark to validate if `node-gameloop` is actually more efficient. I don't wanna put too many dependencies on this project.

Feel free to submit a PR if you'd like to! Cheers!
