### ISSUE TITLE
cluster server

### ISSUE THREAD

**Issue by derwish-pro** [gamestdio/colyseus#102]
Hi. I cloned v0.5.7, and test cluster server usage example. It does not work. No response from server in blowser at localhost:8080/something. I use node v8.7.0.

**Comment by endel** [comment]
@derwish-pro confirmed. seems to be happening on latest version of node indeed. on it.

**Comment by endel** [comment]
For some weird reason, node v8.7.0 is not triggering the `"listening"` event. https://github.com/gamestdio/colyseus/blob/c98f77de3c130df20153983c82b24cfe608bd0f1/src/ClusterServer.ts#L109

This was introduced on #81 

Still investigating.

**Comment by endel** [comment]
Found it, only the http server triggers the `"listening"` callback. The express server doesn't. (https://github.com/gamestdio/colyseus/commit/df2afe4d57f08d9b513039812dcac8201c12e2f2#diff-59c5475edb9c83cd8be23360bc1c004d)

Version `0.5.8` should have fixed this! 

Thanks for reporting!
