### ISSUE TITLE
Benchmark possible improvement using µWebSockets

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus#11]
https://github.com/alexhultman/uWebSockets

**Comment by AnubisCode** [comment]
also wanted to suggest this feature. vote up!

**Comment by TangMonk** [comment]
+1

**Comment by endel** [comment]
Version `0.4.10` is now using µWebSockets 🎉  Please let me know if you experience anything unexpected.

**Comment by AnubisCode** [comment]
works fine for me, thanks!
