### ISSUE TITLE
Server crashing when connected to debugger

### ISSUE THREAD

**Issue by vioint** [gamestdio/colyseus#112]
When attaching the inspector the server always crashes upon the first connection totally disallowing 
debugging the application. The issue seems to relate with inter-process messaging but I didn't find anything in the documentation regarding debugging issues.
When I try adding '--inspect' to nodemon (or even replacing it with node and the same arguments) I am getting the server to run but on the first event emission it fails with an error that kills the process:

=========================================================
user$ npm run dev

> colyseus-unity3d@ dev [code folder]/server_coloseyus
> nodemon --inspect=9330 --harmony ./index.js

[nodemon] 1.14.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --inspect=9330 --harmony ./index.js`
Debugger listening on ws://127.0.0.1:9330/99d13b1a-212c-4737-8b7d-6e2488ab25c0
For help see https://nodejs.org/en/docs/inspector
ClusterServer#register should be called from a worker process.
ClusterServer#register should be called from a worker process.
Listening on 3553
Starting inspector on 127.0.0.1:9330 failed: address already in use
Debugger listening on ws://127.0.0.1:9331/c6f11dc0-4c29-47d2-ab7d-b8eb85b68c9c
For help see https://nodejs.org/en/docs/inspector
Listening on 3553
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:606:16)
    at Server.<anonymous> ([code folder]/node_modules/colyseus/lib/ClusterServer.js:50:24)
    at Server.emit (events.js:159:13)
    at onParserExecuteCommon (_http_server.js:508:14)
    at onParserExecute (_http_server.js:455:3)
[nodemon] app crashed - waiting for file changes before starting...
=========================================================

Can we simply debug this application using nodeJS inspector?

**Comment by endel** [comment]
Hey @vioint, I'm afraid it won't be easy to debug using `ClusterServer`. 

My suggestion is to use `Server` ([see usage](https://github.com/gamestdio/colyseus/blob/master/usage/Server.ts)) for debugging purposes, which doesn't use inter-process communication. For production, `ClusterServer` is recommended.

Cheers!

**Comment by vioint** [comment]
Thanks for the info, I guess this is not easily fixed by any solutions out there, right?
It would be nice to provide this option to devs though and IMHO it should be also noted on the readme as it would have some people scratching their heads/chins...

**Comment by endel** [comment]
Thanks for the input @vioint, I've added some instructions in the [Debugging](https://github.com/gamestdio/colyseus/wiki/Debugging#inspector) wiki page.  Let me know if you have any other consideration! Cheers!
