### ISSUE TITLE
gameServer.fork() should return the array of workers

### ISSUE THREAD

**Issue by seiyria** [gamestdio/colyseus#114]
In my case, I want to make an API that will send a message to all connected nodes. From my understanding, to do this, I need to spawn an express API on each server (already done), add a route that listens for external messages (which would be received by any worker in particular), `process.send` that message to the master, then have the master `worker.send` that to each individual worker. Right now, I can do all but the last step, because `gameServer.fork()` doesn't seem to return anything.

**Comment by endel** [comment]
Hey @seiyria, thanks for the suggestions, it does make sense to return the array of spawned workers. This is available on version [`0.8.4`](https://github.com/gamestdio/colyseus/releases/tag/0.8.4).

I guess you can use the [`memshared`](https://github.com/endel/memshared/blob/master/src/index.ts) project as reference for handling messages from master to child processes. Not sure if express is necessary for your use case. 

Cheers!

**Comment by seiyria** [comment]
Thanks! Express is only necessary because I wanted to have an external API to pass messages, but it's not strictly necessary.
