### ISSUE TITLE
Relation to peer-to-peer Colyseus?

### ISSUE THREAD

**Issue by bgr** [gamestdio/colyseus#12]
Hi,
I've found this project by googling stuff related to [this paper](http://www.cs.cmu.edu/~ashu/gamearch.html). I gave the source code a quick glance and it doesn't seem like this is an implementation of the network described in the paper. Is this an unfortunate name clash?

**Comment by endel** [comment]
Hi @bgr, yes, looks like a name clash. This project does not handle peer-to-peer connections. Cheers!

**Comment by bgr** [comment]
Cool. You might want to add a note to the readme about that. Thanks.
