### ISSUE TITLE
Custom Server Exit Hook

### ISSUE THREAD

**Issue by oyed** [gamestdio/colyseus#120]
Whilst you can listen to the `SIGINT`etc. events, this will not ensure that the custom hook will execute _after_ all of the Rooms have gracefully shutdown. Having an additional, post-Room shutdown hook will better allow for state persistence.

We'd be looking at adding another Promise to the end of the room shutdown promises seen here (https://github.com/gamestdio/colyseus/blob/master/src/MatchMaker.ts#L385)

**Comment by endel** [comment]
Thanks a lot @oyed!  

`Server#onShutdown` and `ClusterServer#onShutdown` are now available on version `0.8.8`.

Wiki page: https://github.com/gamestdio/colyseus/wiki/Graceful-shutdown
