### ISSUE TITLE
Proposal: API Consistency

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus#128]
I'd like to discuss possible changes in the API to make it more intuitive. Here are some suggestions made by @FredDull.

Feel free to leave your suggestions and concerns about changes in the API that could be improved for better readability and consistency. This is not only limited to the `Room` API's, but the entire framework.

### Server-side Room API:

- rename `onMessage(client, data)` to `onData(client, data)`

### Client-side Room API

- rename `onUpdate` to `onStateChange`

## Road to version `0.9.0`

- Agreed API changes will land on version `0.9.0`
- All API changes will be documented in the [migration guide](https://github.com/gamestdio/colyseus/blob/master/MIGRATING.md).

Thoughts? @AnubisCode @seiyria @oyed @havingfunq @darkyen @Federkun @derwish-pro
Cheers!

**Comment by oyed** [comment]
Both `onMessage` and `onData` make sense, as do `onUpdate` and `onStateChange` given the context of being netcode-related, it might be just me so if it improves readability for others I don't see why not.

**Comment by seiyria** [comment]
As it is in the OP, I have no problem with those changes. I'm not sure the value of it, but having the client mirror onDispose (basically call it as part of onLeave) and also add onInit to the client. Again, I'm not sure if that would actually add any value, but something to consider if you want even more consistency.

**Comment by FredDull** [comment]
very nice!

**Comment by Wenish** [comment]
I like the new Names. Even i know i will have to change code lol

I think it would be also nice to change the name of send to sendData

**As a Example how i use it at the moment:**
Client (C# Unity):
```c#
room.Send (new { 
  action = "MOVE_PLAYER_TO",
  payload = new {
    x = 10,
    y = 0,
    z = 10
  }
});
```

Server:
```js
onMessage (client, data) {
    console.log(data);
    this.state[data.action](client, data.payload);
}
```

**Example for update:**
Client (C# Unity):
```c#
room.SendData (new { 
  action = "MOVE_PLAYER_TO",
  payload = new {
    x = 10,
    y = 0,
    z = 10
  }
});
```
Server:
```js
onData (client, data) {
    console.log(data);
    this.state[data.action](client, data.payload);
}
```

If i remeber correctly the server has also a .send method.
this could maybe also be changed to .sendData but i dont use it. maybe someone who uses this has to say something about it...

**Comment by darkyen** [comment]
Late to the party but LGTM.

**Comment by endel** [comment]
I'm working on version `0.9.0`, which the most relevant change is horizontal scalability (#57), and [many other fixes](https://github.com/gamestdio/colyseus/milestone/2).

As the signature of `verifyClient(client, options)` is going to change, I'm thinking of renaming this to `onAuth(options)` - making it similar to other Room's methods. 

Let me know if you have another suggestion!

**Comment by endel** [comment]
On a second thought, I think `onMessage` is the right naming since it just receives the `"message"` event from the WebSocket server. What will change here is `onData` on the clients, which will be renamed to `onMessage` now.

So:
- Client and server have a `send` method name, nothing changes.
- Client and server have an `onMessage` callback. (former `onData` in the client-side)

Any opposing ideas?! 😅 
Cheers!
