### ISSUE TITLE
"not opened" log on socket disconnection

### ISSUE THREAD

**Issue by ghost** [gamestdio/colyseus#13]
Hello,

when a client disconnects from the connection, colyseus throws this error: 

```
Error: not opened
    at WebSocket.send (/home/simon/programming/fps/node_modules/ws/lib/WebSocket.js:218:38)
    at GameServer.broadcast (/home/simon/programming/fps/node_modules/colyseus/lib/room.js:163:34)
    at GameServer.broadcastPatch (/home/simon/programming/fps/node_modules/colyseus/lib/room.js:147:17)
    at GameServer.patch (/home/simon/programming/fps/node_modules/colyseus/lib/room.js:177:10)
    at Timeout.wrapper [as _onTimeout] (timers.js:421:11)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

Is this normal? Am I doing something wrong or do I should post more code in here?

Thanks for any help, Simon

**Comment by endel** [comment]
Hi @simon-matt, this shouldn't be happening. Could you post your code somewhere so I could test in my end? Also, which version of Colyseus and NodeJS are you using? Thanks!

**Comment by simon-matt** [comment]
Hi @endel,

Sources are here: https://gitlab.com/smatt/fps/tree/master/servers/colyseus
Node.JS: 6.3.1
NPM: 3.10.5
Colyseus: 0.4.2

Maybe you can find my mistake :)

**Comment by endel** [comment]
Hey @simon-matt,

Looks like this is a known issue on the [ws library itself](https://github.com/websockets/ws/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22not%20opened%22). Note that this error doesn't stop your server from running. 

I'd recommend to reduce [your patch rate](https://gitlab.com/smatt/fps/blob/ac7ba2b75511ed1bb5d9374016c9288fe18413d5/servers/colyseus/rooms/game_server.js#L11) to avoid flooding the network. If you're targeting LAN networks your 5ms round-trip can be fine. In the public internet I'd recommend using 50ms.

I'll leave this issue open. Maybe using https://github.com/gamestdio/colyseus/issues/11 could solve it. 

(Nice project BTW, good luck!)

**Comment by simon-matt** [comment]
Hi @endel,

I totally forgot to reduce this patch rate :D but it still occurs...
I'll take a look at #11 :)

Thank you :D Hope this grows a bit more :)
