### ISSUE TITLE
Zone & hot update

### ISSUE THREAD

**Issue by GAMEKON** [gamestdio/colyseus#130]
Does it possible to have Zone &
hot script update in colyseus like sfs2x does?
http://docs2x.smartfoxserver.com/Overview/zones-room-architecture

**Comment by endel** [comment]
Hi @GAMEKON, 

Could you describe the usage scenario you need these features?

I'd like to keep the architecture of Colyseus as simple as possible. If there's a need for a feature like this, maybe it's possible to achieve that in a different way.

Cheers

**Comment by GAMEKON** [comment]
zones are different games but use a same websocket port.
Hot update means you don't need to restart the nodejs and websocket engine while update the game logic scripts.

**Comment by endel** [comment]
**zones:**

So, for "zones", you could possibly use different room handler names, right? Each game can be a different registered handler:

```
gameServer.register("shooter_game", MyShooterGameRoom);
gameServer.register("memory_game", MyMemoryGameRoom);
```

**hot updates:**

Hot updates would be a very nice to have, and quite tricky to implement.

Currently, I use `onchange` and `ts-node` to reload my server when my code changes. See the configuration I often use:

```javascript
// package.json
// ...
 "scripts": {
    "start-dev": "onchange 'src/**.ts' -i -d 1000 -- ts-node src/index.ts",
  },
  "devDependencies": {
    "onchange": "^3.0.2",
    "ts-node": "^3.3.0",
    "typescript": "^2.4.2"
  }
// ...
```

It's important to note that by restarting the server you'll lose the connected clients. They'll need to reconnect.

**Comment by GAMEKON** [comment]
thank you
