### ISSUE TITLE
Allow to reconnect client into the room

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus#147]
When the WebSocket connection drops unexpectedly, it should be possible to reconnect that client within a certain timespan, even if the room is locked.

**Scenarios:**

- User closed browser tab accidentaly ([colyseus forum](https://discuss.colyseus.io/topic/71/onleave-timeout/3))
- Mobile device went to sleep mode (locked) ([defold forum](https://forum.defold.com/t/colyseus-multiplayer-game-client-server/17101/2))
- Switching from Wi-Fi networks. (#8)
- ...any unexpected action that closes the WebSocket connection. (#68)

**Comment by endel** [comment]
I've set a poll to gather what you guys think about this feature being enabled by default or not. What do you think?

[![](https://api.gh-polls.com/poll/01CDFXAWAZTHJB7223G5NVM4CN/enabled%20by%20default)](https://api.gh-polls.com/poll/01CDFXAWAZTHJB7223G5NVM4CN/enabled%20by%20default/vote)
[![](https://api.gh-polls.com/poll/01CDFXAWAZTHJB7223G5NVM4CN/disabled%20by%20default)](https://api.gh-polls.com/poll/01CDFXAWAZTHJB7223G5NVM4CN/disabled%20by%20default/vote)

**Comment by endel** [comment]
Hey @dossy @sandrosc @AnubisCode @ruifly2012,

I'd appreciate if you all could vote on the poll at the pull request #154 

Cheers!

**Comment by dossy** [comment]
I voted in favor of on-by-default, although that _breaks backwards compatibility_ in case anyone implemented their own reconnection mechanism in their own codebase, but ultimately for future developers, I think the on-by-default will be the useful behavior.
