### ISSUE TITLE
A couple of general questions

### ISSUE THREAD

**Issue by jesst3r** [gamestdio/colyseus#15]
Greetings, i've a several questions:
1. I'm new to NodeJs and JS (Got previous experience with C#, Java and Cpp), but can you explain me, how to start frontend from a Tanx example? After executing "node start" in the root of tanx project, on listening port at localhost, all what i get is - "Cannot Get" and no frontend loaded.
2. Second question is - is project discontinued? Haven't seen updated for a long time. We're looking for a completed server framework, for our game, and we found that Colyseus as very good canditate to this role.
Thank you.

**Comment by endel** [comment]
Hi @jesst3r, 

Good. This project is not discontinued, I started it on my spare time while making a couple of multiplayer prototypes and I still plan to support and grow it as the community uses and suggest features and improvements.

The tanx prototype has a rather unusual setup, as the frontend depends highly on [PlayCanvas](https://playcanvas.com/project/367035/overview/tanxcolyseus) project. You can fork the project in their website and play around from there.

To build an HTML5 client/server from scratch, I suggest you have a look on the [LD35](https://github.com/endel/LD35) or [tic-tac-toe](https://github.com/endel/tic-tac-toe) as examples.

Don't hesitate to ask questions and share your thoughts here on GitHub issues or on the Gitter channel.

Cheers!
