### ISSUE TITLE
sessionId is undefined when trying to join a room twice, at the same time

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus#151]
> Reported by @axot on the [gitter channel](https://gitter.im/gamestdio/colyseus)

**Scenario:**

```typescript
const client = new Client(...);

const room1 = client.join("handler");
room1.onJoin.add(() => console.log(room1.sessionId)); // => "rkv9juYq6f"

const room2 = client.join("handler");
room2.onJoin.add(() => console.log(room2.sessionId)); // => undefined
```

The reason this happens is because:
- first `join`: client connection [reserves a seat for the `client.id` on the specific room](https://github.com/gamestdio/colyseus/blob/8c5641ad7473015694f17581edd47683b012507c/src/MatchMaker.ts#L134), by generating a `sessionId` for the new websocket connection that's going to happen to connect into the room.
- second `join`: client connection overrides the reserved seat as both have the same `client.id`.
- one of the connection with the rooms, when stablished, won't have the `sessionId` value, because [it's deleted once the first room is successfully connected](https://github.com/gamestdio/colyseus/blob/8c5641ad7473015694f17581edd47683b012507c/src/MatchMaker.ts#L90-L91).

**Comment by dongvanhung** [comment]
I have same bug. Please fix this bug !

**Comment by endel** [comment]
Hey @dongvanhung, which version of Colyseus are you using?

I've tried to reproduce this error, but, apparently, it has been solved on https://github.com/gamestdio/colyseus/issues/156

**Comment by endel** [comment]
Closing as I couldn't reproduce this anymore with the latest version.
