### ISSUE TITLE
Clients Array is undefined on Room disconnect

### ISSUE THREAD

**Issue by jyip** [gamestdio/colyseus#152]
`this.clients` is undefined for me when I call disconnect for my class that extends Room.
`/node_modules/colyseus/lib/Room.js:150`
`let i = this.clients.length;`
`TypeError: Cannot read property 'length' of undefined`

Example:
```
export default class MyRoom extends Room {
  onInit (options) {
        this.autoDispose = false;
        this.clock.setTimeout(this.disconnect, 5000);
    }
}
```

**Comment by endel** [comment]
Hey @jyip, this is a common mistake on JavaScript. It's not recommended to pass functions directly as a reference, unless you explicitly say what the `this` will be whenever the function is called.

The alternatives you have are:

```typescript
this.clock.setTimeout(this.disconnect.bind(this), 5000);
```

```typescript
this.clock.setTimeout(() => this.disconnect(), 5000);
```

Hope this helps! Cheers
