### ISSUE TITLE
onAuth fails when authentication takes more than 2 seconds

### ISSUE THREAD

**Issue by amitport** [gamestdio/colyseus#168]
on room creation the seat is reserved for default 2 seconds (not configurable):
https://github.com/gamestdio/colyseus/blob/5f0176086258e2303da0dea6ec167446f4d3ea0a/src/MatchMaker.ts#L146

Specifically, I'm verifying token signed by Auth0. Their public keys are short lived and the process requires occasionally requesting new public keys from auth0-- this may take more then 2 seconds.

**Comment by endel** [comment]
Confirmed, thanks for reporting @amitport, I'll fix this soon!

**Comment by endel** [comment]
Thanks @amitport, I've increased the default seat reservation time to `3` seconds, and added a `Room#setSeatReservationTime(seconds:number)` method!
