### ISSUE TITLE
Shutdown signal handling should happen outside of Colyseus

### ISSUE THREAD

**Issue by jmeyers91** [gamestdio/colyseus#188]
Colyseus should not be calling `process.exit`. I'm integrating a colyseus server in an existing app that has its own graceful shutdown code, but the colyseus graceful shutdown is cutting off my project's cleanup by killing the process before it has finished. In my opinion, colyseus should just expose a `shutdown` or `dispose` method and leave it up to the container application to decide when to run them.

**Comment by gioragutt** [comment]
How about adding an option to the Colyseus server, something like `shutdownProcessOnSignal`, which is by default `true`, to retrain the existing behaviour, but can be turned to false in order to disable the behaviour you explained above?

**Comment by jmeyers91** [comment]
@gioragutt That sounds like good solution. I submitted a PR.
