### ISSUE TITLE
Re-implement Client waiting for asynchronous Room `onLeave`

### ISSUE THREAD

**Issue by oyed** [gamestdio/colyseus#202]
This was the previous behaviour sometime last year - an asynchronous `onLeave` in the Server-side Room would mean the Client waits for it to complete before firing the `onLeave` event. However, the Client is now automatically disconnected from the Room when calling `onLeave`, not waiting for the Server to finish the asynchronous `onLeave` call.

This means that persisting data between two rooms joined one-after-the-other doesn't work very well, if at all.

Given the `onLeave` Event is emitted client-side when the room connection is dropped, it should be as simple as not disconnecting the Client before `onLeave` has finished.

**Comment by endel** [comment]
This should be refactored not to close the WebSocket connection immediately: https://github.com/gamestdio/colyseus/blob/3f9d8d3415c0c0a5740865d6f090a2230b665312/src/Room.ts#L437-L438

**Comment by endel** [comment]
Hey @oyed, just released [colyseus@0.9.22](https://github.com/gamestdio/colyseus/releases/tag/0.9.22) with a fix for this.

As the connection now keeps open while `async onLeave()` is running, I'm now ignoring all messages the client might still be sending to the server, to avoid potential exceptions in your room handler.

**Comment by oyed** [comment]
@endel Thanks, you're a legend!
