### ISSUE TITLE
rejoin is expired?

### ISSUE THREAD

**Issue by davidhoare** [gamestdio/colyseus#207]
everything was working fine on a test project... now I'm getting this error consistently, but no code has changed:
colyseus.js:2832 colyseus.js: server error: rejoin has been expired for npy0KR3Xc
I've cleared caches, restarted everything... nothing seems to make a difference. 
What does this mean, and how can I fix it?
Thank you!
David

**Comment by endel** [comment]
@davidhoare are you using `allowReconnection` during `onLeave` in the server? The rejoin is only allowed while `allowReconnection` is still pending. Cheers

**Comment by xubowenshizi** [comment]
colyseus.js: server error: rejoin has been expired for wG-jzWwI5
I have the same problem without using allowReconnection

**Comment by oyed** [comment]
I have encountered the same as @xubowenshizi - I can't remember exactly what I did, but either `onAuth`/`onJoin` were failing and/or erroring and this was the reported error.

@xubowenshizi Try debugging your `onAuth`/`onJoin` to see if there are any issues.

**Comment by endel** [comment]
@xubowenshizi you **must** use `allowReconnection` to be able to use `rejoin`. See docs: http://colyseus.io/docs/api-room/#allowreconnection-client-seconds

**Comment by oyed** [comment]
@endel I think it might be a bug in error reporting. I had the same issue - I don't use the reconnection architecture from Colyseus in my game anywhere - however I randomly started getting the `rejoin has been expired` error.

It was something to do with my `onAuth`/`onJoin` failing and/or erroring, fixing that removed the issue.

**Comment by endel** [comment]
If you guys happen to have a project that I can reproduce this please let me know, I've tried and cannot reproduce here using latest versions of client and server. 😭

**Comment by davidhoare** [comment]
turns out I traced my particular issue to an unrelated null variable that was causing a glitch and instead it was reporting this error...
Thanks for looking into it, everyone!

**Comment by Loonride** [comment]
@davidhoare I and a few others seem to have had the same issue for 0.9.22, is that the version of Colyseus you are using? Could you be more specific about your solution in case I'm making a similar mistake? Thanks

**Comment by endel** [comment]
Hey, @Loonride just helped to find the reason for this, apparently when the matchmaker retries in case of an odd situation, the `joinOptions` get mutated inside `matchMaker.onJoinRoomRequest `, then if it retries, it will try to perform a `rejoin` without asking:

https://github.com/gamestdio/colyseus/blob/766497e23eaa5b48a6594df02fd5fcac42498f08/src/Server.ts#L244-L250

Reopening until it gets fixed
