### ISSUE TITLE
Transfer a variable between two TS files

### ISSUE THREAD

**Issue by Framecom** [gamestdio/colyseus#210]
Hello. Since I do not know the TypeScript (TS) badly, I would like to write the server part in JS, but I can’t find an example anywhere. How can I do that?

**Comment by seiyria** [comment]
All of the docs have a JS section, for example: http://colyseus.io/docs/api-server/

**Comment by Framecom** [comment]
And how to connect index.js to Colyseus?

**Comment by seiyria** [comment]
Take a look at the examples: https://github.com/gamestdio/colyseus-examples

**Comment by Framecom** [comment]
Thank you so much! I will try 👍

**Comment by seiyria** [comment]
Yes, but there doesn't need to be. If you remove the types (`:any` and `:boolean`) it is exactly the same as vanilla js.

**Comment by Framecom** [comment]
Sorry for my stupid questions
And what will be the ` import {Room, Client} from "colyseus";  ` on js?

**Comment by seiyria** [comment]
It will be `import {Room, Client} from "colyseus";`

see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by Framecom** [comment]
I get an error:
` (function (exports, require, module, __filename, __dirname) { import { Room, Client } from "colyseus";
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:686:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[nodemon] app crashed - waiting for file changes before starting...
`

**Comment by seiyria** [comment]
This depends entirely on your environment, as this works in most browsers. Your environment might have a different build tool that is causing this to not work correctly (ie, compiling down to <ES6). The easiest way to get this to work is to clone an example and work from there. You can rewrite the TS to JS if that works better for you.

**Comment by Framecom** [comment]
Hmm ... I run this with the `npm start` command from colyseus-examples
Version Node - 11.4.0, almost the last

**Comment by Framecom** [comment]
Updated to the latest (11.5.0) - did not help, the same error.

**Comment by Framecom** [comment]
I have a question again. How do I transfer a variable between two TS files? (the variable is the MySQL connection, it is located in index.js, you must also pass to the commands)

**Comment by Framecom** [comment]
I have a question again. How to transfer a variable between two TS files? (the variable is the MySQL connection, it is in index.js, and you must also pass to the rooms)

**Comment by Framecom** [comment]
need to pass it to the rooms*
