### ISSUE TITLE
Transfer a variable between two TS files

### ISSUE THREAD

**Issue by Framecom** [gamestdio/colyseus#211]
I have a question again. How to transfer a variable between two TS files? (the variable is the MySQL connection, it is in index.js, need to pass it to the rooms)

**Comment by endel** [comment]
Apparently, this question has been answered on Discord. 

Please use [Discord](https://discord.gg/RY8rRS7) or the [Forum](http://discuss.colyseus.io/) for questions! Happy holidays!
