### ISSUE TITLE
Separate HTTP server and Colyseus logic

### ISSUE THREAD

**Issue by charlestati** [gamestdio/colyseus#30]
Hello!

Is there a way to specify the HTTP server after configuring the game server logic?

With Socket.IO we can use the `attach` method:

```javascript
var io = require('socket.io')();

// Then, in bin/www
io.attach(http);
```

If there isn't, could anyone guide me to what should be changed? I noticed the HTTP server is used to set the `onConnect` callback right in the `constructor` of the `Server`. Would changing `this.server` to a new `WebSocketServer` instance and adding `this.onConnect` as a callback to this new instance be enough?

Thanks!

**Comment by endel** [comment]
Hey @charlestati, 

Out of curiosity, what's your use case? Can't you specify the http server (`server` option) or a websocket server (`ws` option) in the constructor?

As socket.io has this option, I'll try to follow it. This evening I'll release a new version having it. Cheers!

**Comment by charlestati** [comment]
Hi @endel!

Thank you very much!

I can't specify the server in the constructor as it is defined in another file. See this Express example:

https://github.com/sequelize/express-example/blob/master/bin/www

It requires the `app` in `/bin/www` and binds it to the HTTP server, which means I could have multiple `www` scripts with different ports or config for example.

**Comment by endel** [comment]
Hey @charlestati!

I've just implemented the `attach` method. It accepts the same argument as the constructor. Now the constructor argument is optional.

Hope this helps! Please don't hesitate to ask questions here or in the Gitter channel if you happen to have some. Cheers!

**Comment by charlestati** [comment]
That's awesome! Thank you @endel!
