### ISSUE TITLE
Null and Undefined are incorrectly sent to clients

### ISSUE THREAD

**Issue by JoaoMosmann** [gamestdio/colyseus#31]
When I set a state property as `undefined` it receives it as a `null`, if I set a property as `null` in the server, the client receives a `Object`

Example:

room.ts
```ts
this.setState({ 
  shouldBeUndefined: undefined,   
  shouldBeNull: null     
});
```

In the client I get the following state
```json
{
  "shouldBeUndefined": null,
  "shouldBeNull": {}
}
```

**Comment by endel** [comment]
Thanks for reporting @JoaoMosmann!

Note that `undefined` will be automatically converted to `null`, though. It's how MessagePack` encoding works. 

Cheers!
