### ISSUE TITLE
Construct 2

### ISSUE THREAD

**Issue by Poea** [gamestdio/colyseus#32]
Does the construct 2 client have all the abilities of the basic js client,i know cs2 uses JS,but i'm not familiar with its api

**Comment by endel** [comment]
Hi @Poea,

Yes, the Construct2 client has exactly the same functionality as the JavaScript client.

The Construct2 client is not "official", and is still using v0.5.2 of the Colyseus client, the latest one is v0.6.0. It was created by @polpoy, I'm sure he'd be glad to receive pull requests :)

**Comment by endel** [comment]
Just noticed that @polpoy updated to version `0.6.0`, that's great! :)

Feel free to re-open this issue and/or post your questions on Gitter channel!
