### ISSUE TITLE
Typescript 

### ISSUE THREAD

**Issue by Phacanu** [gamestdio/colyseus#35]
According to github,most of this is coded in typescript,does this mean users will have to use it for most of the functions that the engine provides or is using js solely feasible ?

**Comment by JoaoMosmann** [comment]
Hi @Phacanu,

You don't have to use Typescript, it works perfectly well just with Javascript. Typescript is just a superset that transpiles to javascript, so basically, the code that you're going to use is pure javascript.

**Comment by Phacanu** [comment]
@JoaoMosmann  Ahh,thanks for clearing that up,thank you!
