### ISSUE TITLE
Bottlenecks and children

### ISSUE THREAD

**Issue by Phacanu** [gamestdio/colyseus#36]
Is their some type of upper limit of concurrent players a room can have?Could rooms be broken up into sub areas so that a player only sees things within a certain area rather than things within the whole room(world).

**Comment by endel** [comment]
Hi @Phacanu,

There's no limit of players per room, by default. You can specify a limit by implementing the `requestJoin()` method in your room handler.

In the current implementation, the **entire** room state patch is broadcasted to every single client connected to it. 

It's possible to send custom data to connected clients manually if you really need to. In the room handler you can send data to a single client, like this:

```typescript
this.send( this.clients[ clientIndex ], { arbitrary: 1, data: 2, here: 3 } );
```

The client will receive this message on the `onData` signal.

Given this, you can implement your own broadcast system for in-area updates. I believe it's possible to have a generic system to allow this, though. I'm definitely interested in having this for the version `1.0.0`.

I'd love to hear ideas of how to implement this, and how the API could look like.

Cheers!

**Comment by Phacanu** [comment]
@endel What about the engine limit,like could this handle 200 or so players on a digital ocean server?

**Comment by endel** [comment]
@Phacanu it pretty much depends on the amount of data your rooms will exchange with your clients. 

You can scale your server using standard node.js + websocket techniques. This blog post has good advice about that: https://blog.jayway.com/2015/04/13/600k-concurrent-websocket-connections-on-aws-using-node-js/ on this blog post, the author is using [socket.io](http://socket.io/). Colyseus uses [uWebSockets](https://github.com/uWebSockets/uWebSockets), which in theory has better performance.

I'm planning to perform a stress test in a real game I'm working on during this week and post the results here :)

**Comment by Phacanu** [comment]
@endel  socket io uses uwebsockets as of the most recent versions,and i'll take a look at that post
