### ISSUE TITLE
how to use lag compensation feature?

### ISSUE THREAD

**Issue by kukuri666** [gamestdio/colyseus#42]
can you give me a simple example lag compensation implementation?

**Comment by endel** [comment]
Hi @kukuri666, I'm planning on releasing some free material on lag compensation and client prediction this year. I can't give you a date for it, but it's definitely on our radar.

**Comment by rozenshtein** [comment]
Does unity example have lag compensation feature?

**Comment by endel** [comment]
Hi @rozenshtein. No, it doesn't. Lag compensation and client prediction are *not easily pluggable*, as the implementation highly depends on what you're trying to achieve.

**Comment by darkyen** [comment]
If this hasn't been done already, I can write a blog post on this.

**Comment by kukuri666** [comment]
@darkyen 
can't wait to read your blog post

**Comment by 486** [comment]
Hi, why was this closed? Is there a blog post somewhere now? Thanks.
