### ISSUE TITLE
Upgrade to node v4 to avoid using --harmony

### ISSUE THREAD

**Issue by rahatarmanahmed** [gamestdio/colyseus#5]
We shouldn't have to use --harmony on our applications to use Colyseus.

#4 should take care of this from a support standpoint, but Colyseus's own npm scripts and documentation still use `--harmony`. I don't want to send a PR removing those yet as that's a pretty opinionated thing, but I think it'd be good to move forward.

Is there anything preventing colyseus from requiring node v4+?

**Comment by endel** [comment]
It seems you already figured out! Thanks for your pull requests! :)
