### ISSUE TITLE
Would Colyseus be viable for a seamless world

### ISSUE THREAD

**Issue by Phacanu** [gamestdio/colyseus#53]

**Comment by Phacanu** [comment]
In its curren

**Comment by endel** [comment]
Hi @Phacanu, yes. You can separate your "world" into different areas, by creating different rooms. When entering/leaving the area you can connect/disconnect from that room.

**Comment by Phacanu** [comment]
@endel  When I asked about a seamless world, I was kind of referring to 1 room holding multiple clients rather than splitting the world up between rooms, And from testing out the example project the way rooms are handled i feel that would break the whole scene

**Comment by endel** [comment]
It depends on how much data will be stored as your room's state.

As the server will compute all the changes and send them as a patch to **all clients** in the room, it may make more sense to split the world into smaller pieces.

Would this be a problem in your scenario? Do you think of having something shared that really needs every client to be in the same room?

**Comment by Phacanu** [comment]
Yes it would, If there was some way to create a system that would allow you to only send data like the way i have it in this quick example it would open up a lot of doors for a large and seamless environment

```
  onMessage (client, data) {
    this.state.updateRange.messages.push(data.message);
    console.log("ChatRoom:", client.id, data);
  }
```
![singleroomenvironent](https://cloud.githubusercontent.com/assets/25750359/26065400/d264ab08-3961-11e7-9104-55673eca90af.png)

**Comment by AnubisCode** [comment]
You can just to do like this:
1) send the data to all clients in the room, but
2) check out the position of the client in each PinkRectangle:

```
pink_rectandgle1 = {aX: 100, aY:100, bX: 200, bY:200};

for(let id in this.entities) {
	entity = this.entities[id];
	if(this.state.checkPosition(entity, pink_rectandgle1)){
		//we are in PinkZone1!
	}
}


checkPosition: function(vEntity, vRectangle){
   return (vRectangle.aX <= vEntity.position.x && vEntity.position.x <= vRectangle.bX && vRectangle.aY<= vEntity.position.y && vEntity.position.y <= vRectangle.bY);
}
```
