### ISSUE TITLE
Support horizontal scalability

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus#57]
Supporting vertical scalability (https://github.com/gamestdio/colyseus/issues/43) introduced an architectural change that can be evolved to supporting horizontal scalability in the future.

Match-making should consider sessions living on different servers/processes to determine where the user should connect to. 

Communication between servers/processes can be achieved by using either [Redis](https://redis.io/) or another message broker such as [uTT](https://github.com/uNetworking/uTT)

In order to achieve horizontal scalability, supporting PM2 for managing processes would be  great to have first (https://github.com/gamestdio/colyseus/issues/56)

**Comment by austinkelleher** [comment]
@endel Is there any update on this? I would really like to see this implemented!

**Comment by takaaptech** [comment]
@endel Me too, Please add this feature as it is very important in production server!

**Comment by endel** [comment]
I'm starting to experiment with horizontal scalability on branch [0.9.0](https://github.com/gamestdio/colyseus/tree/0.9.0). I'll update you guys as soon as I have some tangible progress.

**Comment by endel** [comment]
So, the plan for supporting horizontal scalability is basically allowing connections from other processes/servers to communicate with the process which the room actually lives in.

Previously, only the clients connected to the right process (which the room was spawned) could communicate with that room. Now, client connections could live in any process and communicate with the process which the room is living in. I'm still not sure this will scale properly since the communication through Redis PUB/SUB will increase considerably, even when it's not really necessary. An extra delay of a couple milliseconds will come to play here.

By removing the `ClusterServer` implementation, a lot of issues caused by it will not exist anymore, such as https://github.com/gamestdio/colyseus/issues/74, https://github.com/gamestdio/colyseus/issues/56, https://github.com/gamestdio/colyseus/issues/125, https://github.com/gamestdio/colyseus/issues/126, and https://github.com/gamestdio/colyseus/issues/91.

The good thing about `ClusterServer` is that it was possible to forward connections **from the same server** into the right process. Unfortunately, by using multiple processes spread across multiple servers, it's not possible to customize the load balancing algorithm to redirect clients to the right process.

I'd like to have an adapter for [memshared](https://github.com/endel/memshared) as well (https://github.com/endel/memshared/issues/10), so you wouldn't need to have a Redis instance running if you have a single server with multiple processes.

More details coming soon!

**Comment by endel** [comment]
Redis support implemented on https://github.com/gamestdio/colyseus/pull/135

memshared has been implemented too, but still on experimental stage.
