### ISSUE TITLE
Implement Lua/CoronaSDK client

### ISSUE THREAD

**Issue by takaaptech** [gamestdio/colyseus#6]
This is simple but awesome server for multi player game! Would you please support tcp udp protocol so client write by LUA can connect to server?
Thank so much!

**Comment by endel** [comment]
Hi @takaaptech, thanks for your feedback.

Are you using CoronaSDK? It would be possible to implement a client using [lua-websockets](https://github.com/lipp/lua-websockets) following the (simple) message protocol Colyseus uses.

Cheers

**Comment by takaaptech** [comment]
Thank so much! i will try https://github.com/dmccuskey/DMC-Corona-Library#dmc_websockets

**Comment by endel** [comment]
@takaaptech actually this would take a little effort by abstracting receiving and sending messages using Colyseus's protocol: https://github.com/gamestdio/colyseus/blob/master/lib/protocol.js

I'd really like to have a LUA/CoronaSDK client implemented, so lets leave this issue opened!
[DMC-Corona-Library](https://github.com/dmccuskey/DMC-Corona-Library) seems to be a good starting point, it would be great to have a standalone client for Colyseus though. 

Thanks

**Comment by endel** [comment]
I've started a port from the JavaScript client here: https://github.com/gamestdio/colyseus.lua

For now it works only inside Corona Simulator. It seems that CoronaSDK won't play nice with [luarocks](http://luarocks.org) at all. I'll try to upload a plugin on [3rd party plugin directory](https://store.coronalabs.com/) later this week. Hopefully we'll have this client working on mobile phones soon!

Please let me know if you have any experience on this, I'm not used to LUA ecosystem.
Cheers!

**Comment by endel** [comment]
The CoronaSDK client is now working as expected on Android, probably it will work on iOS devices as well. Please feel free to submit any issues if you find any when testing it! Cheers!

**Comment by takaaptech** [comment]
I confirm that it works well on ios device (tested on ipad mini). Thanks!
