### ISSUE TITLE
Auto-reconnect colyseus.js to server

### ISSUE THREAD

**Issue by seiyria** [gamestdio/colyseus#62]
In my development environment, any time I save/restart the server (I'm using nodemon), it reboots. The client will disconnect and then I have to refresh the page to reconnect. In a live game, this means that if I push an update to the server every player will disconnect and not attempt to reconnect automatically.

Automatic reconnection (with exponential backoff configurable, as [primus has](https://github.com/primus/primus#connecting-from-the-browser)) would help this a lot.

**Comment by endel** [comment]
That'd be useful indeed, thanks for the request @seiyria (I thought we'd have it in the new structure, but this feature is still missing)

**Comment by seiyria** [comment]
any chance this will make it in with an update to the 0.5.x branch?

**Comment by endel** [comment]
hopefully, we'll have it in a couple of weeks!

**Comment by seiyria** [comment]
Right now, this _kinda_ works. If the server reboots, the client will predictably disconnect, and then it will reconnect but it will get BUFFER_SHORTAGE errors. To make this work again, the page has to be refreshed and a new connection has to be created.

**Comment by endel** [comment]
@seiyria can you try [`colyseus.js@0.7.6`](https://github.com/gamestdio/colyseus.js/releases/tag/0.7.6)? 

When reconnecting automatically, the WebSocket was loosing the `binaryType` property. The BUFFER_SHORTAGE was happening because the data was coming as `Blob` instead of `ArrayBuffer`, and couldn't be decoded because of that.

Cheers!

**Comment by seiyria** [comment]
@endel it looks like I will still get it during those other conditions (ie, randomly on joining a room). However, it no longer happens on reset! Instead, I have a fixable error. I'll try to dig in on why this is happening.

**Comment by seiyria** [comment]
This looks like it's working now, with no side effects!

**Comment by endel** [comment]
Closing as this seems to be solved. Feel free to re-open if you'd like to!
