### ISSUE TITLE
How does this differ to deepstream.io?

### ISSUE THREAD

**Issue by jr69** [gamestdio/colyseus#63]
Hi,

I'm just doing some research right now about what libraries I should be using for a HTML5 MMOG (an .io game). I recently came across colyseus and I'm wondering how does it differ to deepstream.io, which is something similar to Firebase? Can the two be used together? Or do they conflict?

Thanks

**Comment by endel** [comment]
Hey @jr69, 

**How does this differ to deepstream.io**
Colyseus has the only focus on multiplayer games, and it should be constantly evolving to this direction. It supports multiple sessions/rooms out of the box, and it's mission is to be easy to use, even if you're new to server-side development. Integration between server/client should be really simple.

You usually don't even think about networking when using Colyseus. Just try to keep your room state small and develop your game.

deepstream.io has some features that Colyseus does not, such as authentication and horizontal scalability (Colyseus can only scale vertically at the moment).

deepstream.io as a whole seems to be in a more mature state, as it seems to be backed by a company. Colyseus is an indie project.

**Can the two be used together?**
No, the usage of one exclude the usage of the other.

It depends on what you're looking for. I'd say Colyseus is easier. deepstream.io on the other hand, could potentially have better performance - which you'll need to think about and do it yourself.
