### ISSUE TITLE
patched states are not broadcasted because previous and new states are always equal

### ISSUE THREAD

**Issue by PiotrChabrosAtos** [gamestdio/colyseus#64]
I am quite a newbie in this, and I am looking for a solution to my problem.

using a custom StateHandler 

myRoom.OnUpdate shows the snapshot of the room's state and it works fine and I can see changes in the state over time

but my clients do not receive any updates of the patched state 
because in the Room.prototype.broadcastPatch function
currentStateEncoded.equals(this._previousStateEncoded) is always equal true,
so the patched state is never broadcasted

plz help!!!

**Comment by endel** [comment]
Hey @PiotrChabrosAtos! 

Not sure if I understood your problem. If your `room.OnUpdate` is triggered over time and you can see the updated state, the patches are being broadcasted successfully. 

You should be able to listen to a particular variable change using [`room.state.listen()`](https://github.com/gamestdio/colyseus.js#listening-to-room-state-change) in the client-side. 

PS: Version `0.7.0` of the client hasn't been released yet and `room.state.listen()` (which is from version `0.6.0`) will be moved to `room.listen()`

**Comment by PiotrChabrosAtos** [comment]
room.OnUpdate is triggered when the room is updated (some of the room variables change)
although the patches are not being broadcasted successfully 
as I have described above, I am not able to retrieve any information about any variable from the room that changes, that I listen to with room.state.listen()
after debugging it shows, that in the function where the patched state should be broadcasted for listening,
in the Room.prototype.broadcastPatch currentStateEncoded.equals(this._previousStateEncoded) is always equal true, so the patched state is never broadcasted!!!

**Comment by endel** [comment]
@PiotrChabrosAtos from your description it looks like the state is not changing. Can you share your room handler?

**Comment by PiotrChabrosAtos** [comment]
exactly. here is my StateHandler.js:

```
var Player = require('./Player')

class StateHandler {

  constructor () {
    this.players = []
    this.messages = []
    //this.mapBuilder = new MapBuilder()
    //this.map = this.mapBuilder.build()
  }

  restart () {
    //this.map = this.mapBuilder.build()
  }

  addPlayer (client) {
    this.players.push(new Player())
  }

  removePlayer (client) {
    delete this.players[client.id];
  }

  addMessage (message) {
    this.messages.push(message)
  }

  toJSON () {
    return {
      messages: this.messages,
      players: this.players
    };
  }

}
module.exports = StateHandler
```

**Comment by PiotrChabrosAtos** [comment]
And here is the Room:

```
var Room = require('colyseus').Room
var StateHandler = require('./StateHandler')

class CasualRoom extends Room {

  constructor (options) {
    super( options )

    // Broadcast patched state to all connected clients at 20fps (50ms)
    this.setPatchRate( 1000 / 20 )

    // // Call this function if you intend to implement delay compensation
    // // techniques in your game
    // this.useTimeline()

    // Call game simulation at 60fps (16.6ms)
    this.setSimulationInterval( this.tick.bind(this), 1000 / 60 )

    // initialize StateHandler
    this.setState(new StateHandler())
  }

  requestJoin(options) {
    //console.log(options);
    // only allow 2 clients per room
    return this.clients.length < 2;
  }

  onJoin (client) {
  	console.log(client.id, "joined the room")
  	this.state.addPlayer(client)
  }

  onMessage (client, data) {
    console.log(client.id, data)
    this.state.addMessage(data)
  }

  tick () {
    //
    // This is your 'game loop'.
    // Inside function you'll have to run the simulation of your game.
    //
    // You should:
    // - move entities
    // - check for collisions
    // - update the state
    //

    // // Uncomment this line to see the simulation running and clients receiving the patched state
    // // In this example, the server simply adds the elapsedTime every 2 messages it receives
    // if ( this.state.messages.length % 3 == 0 ) {
    //   this.state.messages.push(`${ this.clock.elapsedTime }: even`)
    // }
  }

  onLeave (client) {
    console.log(client.id, "left the room")
    this.state.removePlayer(client)
  }

  dispose () {
    console.log("room disposed");
  }

}

module.exports = CasualRoom

```

**Comment by PiotrChabrosAtos** [comment]
But I know the state is changing because I can see the changes in the OnUpdate method

**Comment by PiotrChabrosAtos** [comment]
@endel can we please get in touch on Skype? This most likely a newbie issue so this way it can be resolved quickly

**Comment by endel** [comment]
Thanks for sharing @PiotrChabrosAtos,

First of all, if `OnUpdate` is being triggered, it means the patch came for the client: https://github.com/gamestdio/colyseus.js/blob/0.6.0/src/Room.ts#L56-L77

I see one problem in your `StateHandler` when adding/removing the player from the state. Ideally, you should use an object (`{}`) instead of an array (`[]`) to store them.

```javascript
// StateHandler

constructor () {
  // ...
  this.players = {};
}

addPlayer (client) {
  this.players[ client.id ] = new Player();
}
```

You can add a fallback listener for your state to see all changes that are being triggered. Example:

```typescript
room.state.listen((segments: string[], op: PatchOperation, value?: any) => {
    console.log("Patch coming:", segments, op, value);
})
```

**Comment by PiotrChabrosAtos** [comment]
Hi @endel ,

How can I add this fallback listener?

I have tried using a simple plain object state inside my room:

```
    this.setState({
      messages: []
    })
```

Then, after sending some messages from the clients, the messages are visible in the room.OnUpdate function handler, but there are no messages incoming to room.state.Listen("messages", "add", OnAddMessage); method handler.
