### ISSUE TITLE
Moving Client room-to-room

### ISSUE THREAD

**Issue by oyed** [gamestdio/colyseus#65]
Is this possible? For example, having Rooms as Maps in an MMO game. Once a "door" is triggered, the room will move the player to the next specified room.

**Comment by endel** [comment]
Hi @oyed,

Currently, the only way to achieve this is by manually sending a message from the server to the client you want to move, and, from the client-side, request to join into that room. See dummy example below:

**Server-side:**

```
// "previous_room" handler
this.send(client, { letsMoveTo: "next_room" });
```

**Client-side**

```
var previousRoom = client.join("previous_room");

previousRoom.onData.add(function(data) {
    var nextRoom = client.join(data.letsMoveTo);
});
```

**Comment by oyed** [comment]
@endel Thanks - can I persist Client (Player) Data through rooms?

**Comment by endel** [comment]
@oyed you're welcome! You'd need to persist the user data somewhere in between connections, such as a database or in memory. 

I wouldn't recommend persisting in NodeJS's process, since when upgrading to the next version of the server (`0.6.x`) will break things. In the current version (`0.5.x`) it will be fine because it's a single process. Version `0.6.x` will introduce multiple processes, and your rooms may live in a different process.

**Comment by seiyria** [comment]
This is something I do as well (I have an RPG where each map is a room). Basically, I do it exactly as endel described - I tell the client to teleport, and the client initiates the request. I do some cleanup on the server, save the player, then when it leaves the room and joins the next one, the x, y, etc are already set. When the next version comes out, you'll be able to do promise validation in canJoin which will make it so you can check the database to verify that the map you're on is the map you should be on (for example).

**Comment by oyed** [comment]
Thanks for the help!

**Comment by xfause** [comment]
after 3 years. is there any update?
new method like jumpToRoom()?
or this solution still useable?

**Comment by endel** [comment]
Hi @xfause, there are a couple of different ways of achieving this.

What I do on [mazmorra](https://mazmorra.io) is:
- the server sends a message to the client, with the new level info (e.g. "go to level 7")
- the client receives that message, and disconnects from the previous room, and connects to the next one, given the provided info from the server

A more "secure" way of handling this, would be to use the [`matchMaker` API](https://docs.colyseus.io/server/matchmaker/) in the server-side, and send the "seat reservation" data through a message for the client, and the client can the call [`.consumeSeatReservation()`](https://docs.colyseus.io/client/client/#consumeseatreservation-reservation)

**Comment by arief0303** [comment]
Can someone please elaborate the syntax in detail? Thank you

**Comment by atuncer** [comment]
why can't we force join a client

**Comment by endel** [comment]
@atuncer the problem I see currently in allowing the SERVER to force the client to join is that we don't have a declarative way for the CLIENT to properly listen to this event and set up its callbacks. 

I'm very open to an API/feature proposal to allow this. It would be nice to have this feature for version `1.0` with a good API.
