### ISSUE TITLE
Losing connection to room on unstable connection

### ISSUE THREAD

**Issue by Tazer** [gamestdio/colyseus#68]
Hey, Got into another issue. When the client has kinda flaky connection.

It seems it loses the connection to the room. But not the matchmaking socket, I'm getting the following error: 
`MatchMaking couldn't process message: [ 13, 'SylUUMYDB-', { name: 'Patrik', score: 242 } ]``

In what cases would a _onLeave  ( https://github.com/gamestdio/colyseus/blob/1ecc837de61eca913925cf9eb5a3da8f9704a41c/src/Room.ts#L192 )  trigger ? Cause it seems that's what's happening the "client" disconnects from the room. But then the messages are redirected to the "MatchMaking" socket.

Cause I guess I get into this comment: https://github.com/gamestdio/colyseus/blob/1ecc837de61eca913925cf9eb5a3da8f9704a41c/src/Room.ts#L204

```
 // TODO: force disconnect from server.
    //
    // need to check why the connection is being re-directed to MatchMaking
    // process after calling `client.close()` here
```

What would you suggested approach be to not lost the message on the server ? Cause I'm trying on the client "directly" room leave , join again .. but that doesn't seems to trigger / help.

**Comment by endel** [comment]
Hey @Tazer, 

Can you describe what a "flaky connection" would be? 
When the client disconnects, the room will be destroyed automatically.

I think this issue can be related with the auto-reconnection: https://github.com/gamestdio/colyseus/issues/62

**Comment by FredDull** [comment]
I think he want a support just like this:
http://docs2x.smartfoxserver.com/GettingStarted/reconnection-hrc-plus
Will it be implemented?

**Comment by endel** [comment]
You can now handle client reconnection on version `0.9.7` (https://github.com/gamestdio/colyseus/releases/tag/0.9.7)
