### ISSUE TITLE
is colyseus suitable for turn base game?

### ISSUE THREAD

**Issue by takaaptech** [gamestdio/colyseus#7]
Hi!
I am develop a turn base game (likes tic tac toe online). In game, users start match and play turn by turn, user move is limited by time (e.x 30 second each move) . And after some conditional, match over and then user start match again . So how can i implement this feature in colyseus server?
Thank so much!

**Comment by endel** [comment]
Hi @takaaptech, 

Yes, it's possible. 

I'm starting to write the documentation for the server, you can take a look here: http://gamestd.io/colyseus/docs/room-state.html (feedbacks are welcome!)

Considering you want to make a "tic tac toe" like game, you'd need to [allow only 2 clients per room](http://gamestd.io/colyseus/docs/match-making.html), and the room state might look like this:

```javascript
var Room = require('colyseus').Room
class TicTacToeRoom extends Room {
  constructor (options) {
    super(options, 1000)
    
    this.players = {}
    this.setState({
      currentPlayer: null,
      board: [[0,0,0], [0,0,0], [0,0,0]]
    })
  }

  requestJoin() {
    return this.clients.length < 2
  }

  onJoin(client) {
    this.players[client.id] = (this.clients.length == 1) ? "X" : "O"
  }

  onMessage (client, data) {
    // change this.state.board[x][y] to client's attribute (X or O?)
    this.state.board[x][y] = this.players[client.id]
  }
}

module.exports = TicTacToeRoom
```

I didn't tested this code, just wrote it quickly here. You'd basically have to deal with the board state in the server, and request commands through the client on the position you want to update. When the state has successfully changed, you can apply the change in the client-side through the `patch` callback in the client.

To deal with timing events, you could use built-in `setInterval` and `setTimeout` methods, and switch the `state.currentPlayer` variable. It's also a good idea to check for the `currentPlayer` when accepting movements inside `onMessage` method.

Hope this helps, let me know if you have any questions.

**Comment by takaaptech** [comment]
Thank so much!
