### ISSUE TITLE
Node https Module Support

### ISSUE THREAD

**Issue by oyed** [gamestdio/colyseus#74]
I haven't fully had a chance to test whether it's my setup that's the issue, but in the meantime, I thought I'd open an issue to collate anything I find.

It's definitely a feature that is required in this day and age, especially once #49 is implemented.

**Comment by derwish-pro** [comment]
I'm using SSL in my project. Just created an https server instead of http.

**Comment by derwish-pro** [comment]
SSL stopped working for me when I upgraded to v0.5 (it worked on v0.4).

**Comment by endel** [comment]
Thanks for confirming @derwish-pro, I'll investigate this over the weekend.

**Comment by derwish-pro** [comment]
I think that this bug is most likely related to colyseus-unity3d. I remembered that I used my custom colyseus unity-side implementation, and I used BestHTTP for WebSocket connecton. Maybe that's why it worked for me. It is necessary to check, can the WebSocket-library which is used in colyseus-unity3d  work with SSL?

**Comment by oyed** [comment]
That may be why I was having issues, then. Even before 0.5 release, I was using the 0.5 Alpha.

**Comment by endel** [comment]
Hey, I'm still not sure how to fix this. Here's what I've found so far:

- It's not possible to pass a `TLSSocket` from master to child processes (https://github.com/nodejs/help/issues/865#issuecomment-334999911, https://github.com/nodejs/node/issues/4037)
- It's only possible to pass [`net.Socket`, and other types](https://github.com/nodejs/node/blob/b050c14d91edc6f25983395673f28e785ee60a48/lib/internal/child_process.js#L636-L648)

**Comment by derwish-pro** [comment]
You think the problem is not on the client side?

**Comment by derwish-pro** [comment]
It seems to me that the problem is in the library for the socket.io in colyseus-unity3d.

**Comment by endel** [comment]
@derwish-pro are you using a reverse proxy for https or the `"https"` module in the server-side? Maybe we have 2 problems then! :)

**Comment by derwish-pro** [comment]
No, I use direct connection.

**Comment by endel** [comment]
Hey guys,

I've just tried using nginx's SSL proxy and it worked with both JavaScript and Unity3d clients - by connecting to `wss://` protocol: https://github.com/gamestdio/colyseus/wiki/Deployment#nginx-configuration-with-ssl

Apparently proxying from HTTPS (nginx) to HTTP (node) works fine.

Ideally, it **should** be possible to use the `https` module directly (without nginx) but I'm still not sure how to handle passing the `tls.TLSSocket` to a child process.

Cheers!

**Comment by oyed** [comment]
Thanks for investigating @endel - I'll move over to proxying the request.

**Comment by derwish-pro** [comment]
Thank you, I will use this approach in production.


От: Endel Dreyer
Отправлено: 13 октября 2017 г. в 21:07
Кому: gamestdio/colyseus
Копия: Derwish; Mention
Тема: Re: [gamestdio/colyseus] SSL Support(?) (#74)

Hey guys,
I've just tried using nginx's SSL proxy and it worked with both JavaScript and Unity3d clients - by connecting to wss:// protocol: https://github.com/gamestdio/colyseus/wiki/Deployment#nginx-configuration-with-ssl
Apparently proxying from HTTPS (nginx) to HTTP (node) works fine.
Ideally, it should be possible to use the https module directly (without nginx) but I'm still not sure how to handle passing the tls.TLSSocket to a child process.
Cheers!

**Comment by endel** [comment]
`ClusterServer` has been deprecated and this issue shouldn't happen anymore (https://github.com/gamestdio/colyseus/pull/135)
