### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by gregmax17** [gamestdio/colyseus#75]
Just sharing our email for everyone if they come across this...

Firstly, thanks for making a quick and handy websocket framework! I greatly appreciate the work you are contributing.

My question is having to do with groups in rooms, or multiple rooms. Can I explain my scenario and maybe you can tell me how to approach it?

In my game I would like to have multiple rooms available, max per room is 8 players. So how do I create rooms dynamically or find rooms that are available to join when a new player comes? Also, lets say after a match/game a player or two leaves the room (A), how can I put the remaining players in that room (A) into a new room (B) that is waiting? Does this make sense?

Are any of these tasks doable or what kind of approach do you suggest?

I would really appreciate your help and guidance on this (maybe a few snippets of code for example). I'm really new to web sockets, but have some experience with game dev. I just need some good examples for my situation to get going.

Thanks again!

> The matchmaking will handle joining/creating rooms automatically. By setting the [maxClients property](https://github.com/gamestdio/colyseus/wiki/Room-API#public-properties) to 8, whenever a new client tries to join that room, and all the available rooms are full, a new one will be created. 

> Unfortunately, currently, there's no way to redirect players from one room to another from the server.  You could achieve this by manually making the client connect to a new room/session, in case the number of players is low, for example. 

> Moreover, from the client-side, there's no built-in method to retrieve the number of rooms available and number of clients connected to them. If you really need this feature, though, it shouldn't be hard to make it yourself - by exposing this data in a HTTP request, for example. (Discussion on this at #10)[https://github.com/gamestdio/colyseus/issues/10]

> Here's a an implementation to expose the rooms available in the server in a HTTP request, using the data already available in the server: (https://gist.github.com/endel/fcbee58cf35b081afb237b0b3e264e35)[https://gist.github.com/endel/fcbee58cf35b081afb237b0b3e264e35]

> You can prioritize rooms with a higher number of players by returning a number (from 0 to 1) in the [requestJoin method](https://github.com/gamestdio/colyseus/wiki/Match-making#ranked-matches).

**Comment by gregmax17** [comment]
What do you mean "a new one will be created"? How is a new room created and does it give it a new name or something? I'm looking at the code in the examples and it just register's one room with the name of "chat". Do I need to make 20+ rooms initially? 

On this tut page, (Room Handlers)[https://github.com/gamestdio/colyseus/wiki/Room-handlers], I implemented the `requestJoin` method, but it seems that there is no property of `options` and instead used:

```
requestJoin () {
  return this.clients.length < this.maxClients;
}
```

This would error though after I reached the `maxClients` limit, I'm assuming it was creating another room?

Sorry, I'm just trying to wrap my head around the flow of all of this.

**Comment by endel** [comment]
Hey @gregmax17!

> What do you mean "a new one will be created"? How is a new room created and does it give it a new name or something? 

I meant a new room instance. You can have multiple instances of the "chat" room, even though you only registered it once. This is handled internally by the framework.

> This would error though after I reached the maxClients limit, I'm assuming it was creating another room?

The `maxClients` property is [handled automatically](https://github.com/gamestdio/colyseus/blob/c59901e637fc7538f3ea4267a81360c26300e2ee/src/MatchMaker.ts#L167-L171) - if the limit wasn't reached yet, the `requestJoin` will be called - which you can use to handle custom parameters.

For example, you can have a single room handler, that handles multiple kinds of maps.

**server-side**

```
class MapHandler extends Room {
  onInit (options) {
      this.map = options.map;
  }

  requestJoin (options) {
    return options.map === this.map;
  }
}
// ...
gameServer.register("map", MapHandler);
```

**client-side**

```
var forest = client.join("map_handler", { map: "forest" })
var mountains = client.join("map_handler", { map: "mountains" })
```

Hope this helps!
Cheers!

**Comment by endel** [comment]
@gregmax17 feel free to reopen this if you have any other question!
