### ISSUE TITLE
Room#onDispose as a Destructors?

### ISSUE THREAD

**Issue by Federkun** [gamestdio/colyseus#78]
Should `onDispose` be executed when a room can't be created? When immediately after the room initialization `requestJoin` returns `false`, the room will be discarded without calling any additional callbacks. But `onInit` was performed, without however never calling `onDispose`.
It's seems odd to me, maybe it should be called here:
https://github.com/gamestdio/colyseus/blob/06e394fe455121c6c160e20e99449ce8ef24f174/src/MatchMaker.ts#L217

Some thoughts about that?

**Comment by endel** [comment]
You're right! Calling the disposal of the room would make sense!
