### ISSUE TITLE
React Native client?

### ISSUE THREAD

**Issue by Jonovono** [gamestdio/colyseus#89]
Has anyone used this with react native as the client? Not sure exactly what would have to be done to make it work.

**Comment by seiyria** [comment]
You should just need a persistent service that's imported everywhere (ie, a singleton) for this to work. That's how I use it in angular2.

**Comment by endel** [comment]
@Jonovono provided more information about this issue in the JavaScript client: https://github.com/gamestdio/colyseus.js/issues/11

Sorry for being a bit away lately, I've moved from Germany back to Brazil and I plan to focus on Colyseus next month.

**Comment by endel** [comment]
See https://github.com/gamestdio/colyseus.js/issues/11#issuecomment-333332423
