### ISSUE TITLE
Please support BOT api

### ISSUE THREAD

**Issue by takaaptech** [gamestdio/colyseus#9]
Hi,
I think it is very hard to grow up user from zero. So in Match-making please support bot to play with user.
With that feature, we can implement simple bot and simple rules (e.x after 10s if we can not match a user with another real user, we will create a bot instance and user can play with).
Thanks!

**Comment by endel** [comment]
Hi @takaaptech,

That's a great idea, but I don't think this would be part of the core soon. There's a plenty of use-cases out there, and I don't really know the best API for dealing with BOTs right now.

For now, you can handle this by using `setTimeout` when the first player connects, for example.

**Comment by takaaptech** [comment]
OK thanks @endel !
