### ISSUE TITLE
Any idea why this wouldn't work on Zeit Now?

### ISSUE THREAD

**Issue by Jonovono** [gamestdio/colyseus#90]
I am trying to deploy to : https://zeit.co/now

But when I try to connect to the websocket nothing seems to happen. They support websockets so I am not sure why it wouldn't work.

**Comment by endel** [comment]
I haven't tried to deploy on Zeit yet, but since the framework requires to spawn child processes, it's likely that it would work only with the paid version. Heroku has the same limitation.

**Comment by endel** [comment]
@Jonovono just created a new issue for this: https://github.com/gamestdio/colyseus/issues/92

**Comment by Jonovono** [comment]
Awesome, thanks!

**Comment by endel** [comment]
@Jonovono the latest version (`0.5.6`) is now deployable on Zeit, Heroku, etc! Thanks for your input!

**Comment by Jonovono** [comment]
Amazing @endel, thanks!
