### ISSUE TITLE
Colyseus Is Disposing Room While Sending joinRoomResponse to Process.ts

### ISSUE THREAD

**Issue by havingfunq** [gamestdio/colyseus#91]
When i get disconnected by my hosting(cloud9), Colyseus does not recognize this disconnect immediately. The client.on('close', ... ) in Worker.ts is not activated until a client.send(...) in Process.ts. This .send happens during sending a joinRoomResponse to Process.ts. When the socket disconnect callback is invoked, only then does it disposes the room. It sees that their is zero users in the room because the rejoin has not fully registered in the server. This is in the case where there is one user in the server. Its really held back my development progress. 

Perhaps the disconnect could be emitted earlier, there by disposing the room at a better time.

**Comment by endel** [comment]
Thanks for reporting @havingfunq! 

> **From Gitter channel:**
> maybe the framework is not yet dealing well with disconnections via server timeout, I need to check that!

**Comment by endel** [comment]
Quote from @havingfunq:

> https://stackoverflow.com/questions/35503895/nodejs-websocket-detect-disconnected-socket <<there are some solutions here, i dont know how much cruft it will introduce to your server

**Comment by havingfunq** [comment]
https://stackoverflow.com/questions/6404008/how-to-detect-a-tcp-socket-disconnection-with-c-berkeley-socket

You want to write to a socket to check a network timeout. If I can make a clean edit I will issue a pull request.

**Comment by endel** [comment]
`ClusterServer` has been deprecated and this issue shouldn't happen anymore (https://github.com/gamestdio/colyseus/pull/135)
