### ISSUE TITLE
Unity client not working on android device?

### ISSUE THREAD

**Issue by shophk** [gamestdio/colyseus#94]
Reference files https://github.com/gamestdio/colyseus-unity3d
Tested in the editor it works fine.
Build to Android apk, cannot connect with server. 
 Will it be fixed? Or there is something missing or I need to do? Please help.

**Comment by endel** [comment]
Hi @shophk, are you sure you're not using an unreachable address (`localhost`, or local ip without being on the same network) while running on your mobile device?

**Comment by derwish-pro** [comment]
I use colyseus 0.5 and Unity 2017.1. In my case, everything works fine both on iOS and Android.

**Comment by derwish-pro** [comment]
You can try to check it in Android emulator on your dev-machine.

**Comment by hdev72** [comment]
hello
i hame Local schema mismatch from server. error only in android build.
in editor when i running game every thing is ok.
