### ISSUE TITLE
Server crashes when invalid client id tries to reconnect

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus#98]
**How to reproduce:**

1. Have the JavaScript client running
2. Turn off the server
3. Turn on the server
4. When client tries to reconnect the server crashes

Version: 0.5.x

**Comment by stylesuxx** [comment]
Running into the same error. Are you by any chance looking into this, otherwise I could give it a try...

**Comment by endel** [comment]
This problem is somewhat related to https://github.com/gamestdio/colyseus/issues/62 

When the client tries to reconnect to a non-existing room id, the server is currently crashing.

**Comment by endel** [comment]
Server is not crashing anymore when reconnecting.
