### ISSUE TITLE
Time control

### ISSUE THREAD

**Issue by Zyles** [gamestdio/colyseus#99]
Hi,

Not sure if this is the right place to ask. But I am looking to make a multiplayer strategy game (think Europa Universalis 4), with a world map and units moving around.

I want the ability for players to pause the game, and adjust the time scale, (normal, fast, fastest) in the same way that game does.

This essentially means you need to be able to speed up the simulation on the server. I am not completely sure how to approach it yet.

Is this something that can be done with this platform, or is it out of scope?

Thanks.

**Comment by endel** [comment]
Hi @Zyles,

That's totally up to your implementation in the server-side. You can totally do it.

As you mentioned, you can increase the simulation time by calling [`setSimulationInterval()`](https://github.com/gamestdio/colyseus/wiki/Room-API#public-methods)

Feel free to re-open this issue if you have any other question.
Cheers!
